cask_args appdir: '/Applications'

tap 'cszatmary/tap'
tap 'dbcli/tap'
tap 'github/gh'
tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-versions'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'jesseduffield/lazydocker'
tap 'touchbistro/tap'

# macOS only
if OS.mac?
    brew 'dockutil'
    brew 'reattach-to-user-namespace'
end

brew 'autojump'
brew 'awscli'
brew 'bat'
brew 'circleci'
brew 'cmake'
brew 'deno'
brew 'dot'
brew 'exa'
brew 'fd'
brew 'fzf'
brew 'gh'
brew 'git-lfs'
brew 'glances'
brew 'gnupg'
brew 'gnutls'
brew 'go'
brew 'htop'
brew 'httpie'
brew 'jq'
brew 'lazydocker'
brew 'litecli'
brew 'magic-wormhole'
brew 'nasm'
brew 'nmap'
brew 'node@20'
brew 'openssl'
brew 'pgcli'
brew 'python'
brew 'readline'
brew 'ripgrep'
brew 'ruby'
brew 'rust'
brew 'shellcheck'
brew 'speedtest-cli'
brew 'sphinx-doc'
brew 'sqlite'
brew 'tb'
brew 'thefuck'
brew 'tldr'
brew 'tmux'
brew 'tree'
brew 'vim'
brew 'wget'
brew 'xz'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'

cask 'azure-data-studio'
cask 'docker'
cask 'flux'
cask 'iterm2'
cask 'plex'
cask 'postman'
cask 'rocket'
cask 'slack'
cask 'visual-studio-code'
cask 'xquartz'
