# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="spaceship"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM="$HOME/.dotfiles/zsh"
SPACESHIP_ROOT="$HOME/.dotfiles/zsh/themes/spaceship-prompt"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Add wisely, as too many plugins slow down shell startup.
plugins=(git git-extras autojump brew vi-mode)

PKG_PREFIX=/usr
# Load homebrew completion
if type brew &>/dev/null; then
    PKG_PREFIX="$(brew --prefix)"
    FPATH=$PKG_PREFIX/share/zsh/site-functions:$FPATH
fi

# if [[ "$OSTYPE" == "linux-gnu" ]]; then
#     export TERM=xterm-256color
#     eval $(ssh-agent)
# fi

source $ZSH/oh-my-zsh.sh

export PATH="$(go env GOPATH)/bin:$PATH"

# Set vim as the default editor
export EDITOR='vim'

eval "$(fnm env)"
eval "$(thefuck --alias)"
eval "$(fzf --zsh)"

[ -f "$PKG_PREFIX/etc/profile.d/autojump.sh" ] && . "$PKG_PREFIX/etc/profile.d/autojump.sh"
source "$PKG_PREFIX/share/zsh-autosuggestions/zsh-autosuggestions.zsh"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/chrisszatmary/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/chrisszatmary/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/chrisszatmary/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/chrisszatmary/google-cloud-sdk/completion.zsh.inc'; fi

# This must be last
source "$PKG_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
